fixed getAllCategories
jsr1611/houzing-app pull request #87
Opened 2022-05-26 16:39 UTC by azizovmukhammad

2022-05-27 00:37 UTC, jsr1611 commented on src/main/java/uz/digitalone/houzingapp/service/impl/CategoryServiceImpl.java
> +
Shu qismini nega o'zgartirganizni aytsangiz keyin merge qilaman buni

2022-05-27 00:39 UTC, jsr1611 approved these changes

2022-05-27 00:42 UTC, jsr1611 requested changes
CategoryServiceImpl dagi o'zgarishlarni nega qilganizni tushuntirib yozing. Keyin merge qilamiz,
Chunki oldingi holati menimcha yaxshiroq edi.
Nima bo`lganda ham Entity ni to'g'ridan to'g'ri return qilmaslik kerak.

2022-05-27 04:30 UTC, azizovmukhammad commented on src/main/java/uz/digitalone/houzingapp/service/impl/CategoryServiceImpl.java
> +
ha buni Sardor aka aytdi pageableda ham huddi shu qaytgan ekan Sardor aka bizga shu holatni qaytarib bering dedi

2022-05-27 04:32 UTC, azizovmukhammad commented on src/main/java/uz/digitalone/houzingapp/service/impl/CategoryServiceImpl.java
> +
ha buni Sardor aka aytdi pageableda ham huddi shu qaytgan ekan Sardor aka bizga shu holatni qaytarib bering dedi

2022-05-30 07:40 UTC, jsr1611 commented on src/main/java/uz/digitalone/houzingapp/service/impl/CategoryServiceImpl.java
> +
OK

2022-05-30 07:40 UTC, merged